name: lane-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=2.0.0
  - matplotlib>=3.9.0
  - opencv>=4.10.0
  - jupyter>=1.1.0
  - jupyterlab>=4.2.0
  - ipython>=8.26.0
  - notebook>=7.2.0
  - pillow>=10.4.0
  - pandas>=2.2.0
  - scipy>=1.14.0
  - seaborn>=0.13.0
  - tqdm>=4.66.0
  - scikit-image>=0.24.0
  - pip
  - pip:
    - moviepy>=2.1.2
    - imageio>=2.35.0
    - imageio-ffmpeg>=0.5.0
    - ffmpeg-python>=0.2.0 