name: lane-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=2.2.6
  - matplotlib>=3.10.0
  - opencv>=4.11.0
  - jupyter>=1.1.0
  - jupyterlab>=4.4.3
  - ipython>=9.3.0
  - notebook>=7.4.3
  - pillow>=11.2.1
  - pandas>=2.3.0
  - scipy>=1.15.3
  - seaborn>=0.13.2
  - tqdm>=4.67.1
  - scikit-image>=0.25.2
  - pip
  - pip:
    - moviepy>=2.2.1
    - imageio>=2.37.0
    - imageio-ffmpeg>=0.6.0
    - ffmpeg-python>=0.2.0 